### PR TITLE
Webots gradle plugin

### PR DESCRIPTION
**Pull request by brettle**
@alexander-mcdowell, if this works for you on a Mac and on a PC with a system-level install of Webots, please merge. If not, let me know what problems you are seeing. Thanks!

To test:

1. Switch to the webots-gradle-plugin branch
2. (Re)start the webots simulator manually (not via the bat file)
3. Run "Simulate Robot Code on Desktop" from VSCode (selecting the halsim_gui dll as usual)
4. Confirm you make the simulated robot run the autonomous routine by putting it is Autonomous mode with the wpilib sim gui

### CODE REVIEW

**Comment by alexander-mcdowell** [comment]
Getting the following issue when I run "WPILib: Simulate Robot Code on Desktop":
```
java.io.IOException: cscorejni could not be loaded from path or an embedded resource.
        attempted to load for platform /osx/x86-64/
Last Load Error: 
/Users/Lex/RobotCode/SparkMaxSimExample/build/tmp/jniExtractDir/libcscorejni.dylib: dlopen(/Users/Lex/RobotCode/SparkMaxSimExample/build/tmp/jniExtractDir/libcscorejni.dylib, 1): Library not loaded: /usr/local/opt/glib/lib/libgthread-2.0.0.dylib
  Referenced from: /Users/Lex/RobotCode/SparkMaxSimExample/build/tmp/jniExtractDir/libopencv_highgui.3.4.dylib
  Reason: image not found

        at edu.wpi.first.wpiutil.RuntimeLoader.loadLibrary(RuntimeLoader.java:84)
        at edu.wpi.cscore.CameraServerJNI.<clinit>(CameraServerJNI.java:39)
        at edu.wpi.first.wpilibj.RobotBase.startRobot(RobotBase.java:393)
        at frc.robot.Main.main(Main.java:27)
```
Haven't figured out why this is yet. I thought cscorejni was one of the libraries that wpilib automatically loads. Perhaps it's trying to load a .dll file instead of a .dylib file which has a different name? I'll look into it some more.

Edit: Looks like there is a libcscorejni.dylib instead of a cscorejni.dylib. Weird that it's trying to load the wrong version of the library.

**Comment by brettle** [comment]
I suspect that there is a webots version of opencv that is conflicting with a wpilib version. Please do the following to help me diagnose:

1. Switch back to the master branch (to avoid using the plugin for the moment)
2. Run "Simulate Robot Code on Desktop" from VSCode (selecting the halsim_gui dll as usual).
3. Post a list of all the dylibs in `./build/tmp/jniExtractDir` and a list of all the dylibs in `/Applications/Webots.app/lib/controller`

**Comment by alexander-mcdowell** [comment]
Sorry for the late reply. I have been pretty busy today. Here are the dylibs that are in `./build/tmp/jniExtractDir/` on the master branch:
```
libcscore.dylib
libcscorejni.dylib
libntcore.dylib
libntcorejni.dylib
libopencv_calib3d.3.4.dylib
libopencv_core.3.4.dylib
libopencv_features2d.3.4.dylib
libopencv_flann.3.4.dylib
libopencv_highgui.3.4.dylib
libopencv_imgcodecs.3.4.dylib
libopencv_imgproc.3.4.dylib
libopencv_java347.dylib
libopencv_ml.3.4.dylib
libopencv_objdetect.3.4.dylib
libopencv_photo.3.4.dylib
libopencv_shape.3.4.dylib
libopencv_stitching.3.4.dylib
libopencv_superres.3.4.dylib
libopencv_video.3.4.dylib
libopencv_videoio.3.4.dylib
libopencv_videostab.3.4.dylib
libwpiHal.dylib
libwpiHaljni.dylib
libwpimath.dylib
libwpimathjni.dylib
libwpiutil.dylib
libwpiutiljni.dylib
```
And for Webots:
```
libdriver.dylib
libcar.dylib
libController.dylib
libCppCar.dylib
libCppController.dylib
libCppDriver.dylib
libJavaController.jnilib
libvehicle.jnilib
```
I am currently in the process of repairing VSCode because I just noticed that I am getting warnings that my VSCode installation is corrupted. Not sure how this happened... I'll probably end up completely reinstalling vscode and wpilib.

**Comment by alexander-mcdowell** [comment]
If I add the following lines to Main on the webots-gradle-plugin branch:
```
System.load("/Users/Lex/RobotCode/SparkMaxSimExample/build/tmp/jniExtractDir/libcscorejni.dylib");
System.load("/Users/Lex/RobotCode/SparkMaxSimExample/build/tmp/jniExtractDir/llibopencv_highgui.3.4.dylib");
```
The error about cscorejni goes away except that I get this new error:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /Users/Lex/RobotCode/SparkMaxSimExample/build/tmp/jniExtractDir/libcscorejni.dylib: dlopen(/Users/Lex/RobotCode/SparkMaxSimExample/build/tmp/jniExtractDir/libcscorejni.dylib, 1): Library not loaded: /usr/local/opt/glib/lib/libgthread-2.0.0.dylib
  Referenced from: /Users/Lex/RobotCode/SparkMaxSimExample/build/tmp/jniExtractDir/libopencv_highgui.3.4.dylib
  Reason: image not found
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2617)
        at java.base/java.lang.Runtime.load0(Runtime.java:767)
        at java.base/java.lang.System.load(System.java:1831)
        at frc.robot.Main.main(Main.java:27)
```
I tried to find the directory `/usr/local/opt/glib/` but it doesn't seem to exist. Not sure what library this is a part of. Whatever it is, I feels like it should have been automatically installed with wpilib.

**Comment by alexander-mcdowell** [comment]
Seems like using Homebrew to run `brew install glib` and adding `"**/*.jnilib"` to the list `dllPatterns` in `WebotsPlugin/addNativeDesktopLibs(Project project, String libDir)` fixed the problem (it also seemed to fix the problem where we needed to manually load those two packages - not sure why that is). The only error I am getting now is that SparkMaxDriver is not found in the class path, but this is a separate issue since I don't think SparkMaxDriver is compiled for Macs anyway - we'll have to do something similar to what I did with the talons.

**Comment by brettle** [comment]
Thanks @alexander-mcdowell! I've added the jnilibs per your suggestion. The missing libgthread is an issue with the development and beta versions of wpilib because it occurs even with example projects that aren't doing anything with webots. I've reported it in a "Task 3" report on the beta site.

**Review by alexander-mcdowell — APPROVED** [review]

**Pull request merged**
